import type { Metadata } from "next";

import { BaseLayout } from "@/src/ui/components/BaseLayout";

import { Syne } from "next/font/google";
import '@/src/styles/index.css'


const syne = Syne({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${syne.className} p-4 text-blackM`}>
        <BaseLayout>
          {children}
        </BaseLayout>

      </body>
    </html>
  );
}
