import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { BaseLayout } from '@/src/ui/components/BaseLayout';

import '@/src/styles/index.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <BaseLayout>{children}</BaseLayout>
            </body>
        </html>
    );
}

